
# https://taskfile.dev
---
version: '3'

dotenv: ['.env']

vars:
  ONTOLOGY_URI: "http://nubbekg.aksw.org/ontology#"
  ONTOLOGY_FILE: nubbe_schema_1_1_0.ttl

tasks:

  default:
    summary: |
      Just a list of documented tasks.
    silent: true
    cmds:
      - task --list

  validate:prepare:
    desc: Prepare the validation job
    cmds:
      - echo "Working on:" $CMEM_BASE_URI
      - cmd: cmemc vocabulary uninstall {{.ONTOLOGY_URI}}
        ignore_error: true
      - cmemc vocabulary import {{.ONTOLOGY_FILE}}

  validate:
    desc: Validate the Ontology
    deps: [validate:prepare]
    vars:
      VALIDATION_ID:
        sh: echo $(set -a && source .env && set +a && cmemc graph validation execute --wait --id-only {{.ONTOLOGY_URI}})
    cmds:
      - >
        cmemc graph validation inspect {{.VALIDATION_ID}}
      - >
        cmemc graph validation export {{.VALIDATION_ID}}
        --format JSON
        --output-file {{.ONTOLOGY_FILE}}.json
        --exit-1 never

